// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VodLib.models
{
    [Keyless]
    public partial class includes
    {
        public int movie_id { get; set; }
        public int subscription_id { get; set; }

        [ForeignKey("movie_id")]
        public virtual Movie movie { get; set; }
        [ForeignKey("subscription_id")]
        public virtual Subscription subscription { get; set; }
    }
}