// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VodLib.models
{
    [Index("movie_id", Name = "movie_movie_id_uindex", IsUnique = true)]
    public partial class Movie
    {
        [Required]
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(100)]
        public string description { get; set; }
        public bool is18plus { get; set; }
        [Key]
        public int movie_id { get; set; }
        [StringLength(20)]
        public string type { get; set; }
        public decimal duration { get; set; }
    }
}