// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VodLib.models
{
    [Index("order_id", Name = "order_order_id_uindex", IsUnique = true)]
    public partial class Order
    {
        [Required]
        [StringLength(20)]
        public string payment { get; set; }
        [Key]
        public int order_id { get; set; }
        [Required]
        [StringLength(20)]
        public string shipment { get; set; }
        public int client_id { get; set; }
        public int subscription_id { get; set; }

        [ForeignKey("client_id")]
        [InverseProperty("Order")]
        public virtual Client client { get; set; }
        [ForeignKey("subscription_id")]
        [InverseProperty("Order")]
        public virtual Subscription subscription { get; set; }
    }
}