// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VodLib.models
{
    [Index("subscription_id", Name = "subscription_subscription_id_uindex", IsUnique = true)]
    public partial class Subscription
    {
        public Subscription()
        {
            Order = new HashSet<Order>();
        }

        [Key]
        public int subscription_id { get; set; }
        [StringLength(100)]
        public string description { get; set; }
        [StringLength(20)]
        public string name { get; set; }
        public decimal? cost { get; set; }

        [InverseProperty("subscription")]
        public virtual ICollection<Order> Order { get; set; }
    }
}