// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VodLib.models
{
    [Keyless]
    public partial class view_allclientsover18
    {
        public string name { get; set; }
        public DateOnly? dateofbirth { get; set; }
    }
}