// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Drwal_SEW_Projekt_EF.Models
{
    public partial class Client
    {
        public Client()
        {
            Order = new HashSet<Order>();
        }

        public int ClientId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public string Postalcode { get; set; }
        public DateOnly Dateofbirth { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}