// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Drwal_SEW_Projekt_EF.Models
{
    public partial class Includes
    {
        public int MovieId { get; set; }
        public int SubscriptionId { get; set; }

        public virtual Movie Movie { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}