// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Drwal_SEW_Projekt_EF.Models
{
    public partial class MaterializedMegamoviesforkids
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public decimal? Duration { get; set; }
    }
}