// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Drwal_SEW_Projekt_EF.Models
{
    public partial class Order
    {
        public string Payment { get; set; }
        public int OrderId { get; set; }
        public string Shipment { get; set; }
        public int ClientId { get; set; }
        public int SubscriptionId { get; set; }

        public virtual Client Client { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}