// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Drwal_SEW_Projekt_EF.Models
{
    public partial class Subscription
    {
        public Subscription()
        {
            Order = new HashSet<Order>();
        }

        public int SubscriptionId { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public decimal? Cost { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}