// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Drwal_SEW_Projekt_EF.Models
{
    public partial class ViewAllclientsover18
    {
        public string Name { get; set; }
        public DateOnly? Dateofbirth { get; set; }
    }
}